<a href="https://colab.research.google.com/github/khanhtran94/LearnConda/blob/master/Exp1_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import tensorflow as tf

In [6]:
# explain the concept of constant using tensorflow code
a = tf.constant(3)
b = tf.constant(5)

c = a + b

tf.InteractiveSession()
print(c.eval())

# invoke the session so that computational graph will be executed
with tf.Session() as sess:
  var1 = sess.run(c)
  print(var1)

8
8


In [0]:
# Explain the concept of variables used in tensorflow codes

a = tf.Variable(0, name = 'input')
b = tf.constant(1)

mid_value = tf.add(a,b)
update_value = tf.assign(a, mid_value)

tg = tf.initialize_all_variables()

with tf.Session() as sess:
  sess.run(tg)
  print(sess.run(a))
  print("!")
  for i in range(3):
    sess.run(update_value)
    print(sess.run(a))

In [13]:
# next role placeholder in tensorflow

x = tf.placeholder("float32", None)
y = x**2

with tf.Session() as sess:
  result = sess.run(y, feed_dict = {x : [1,2,3,4,5]})
  print(result)

[ 1.  4.  9. 16. 25.]


In [17]:
# next role placeholder in tensorflow

x = tf.placeholder("float64", [None, 3])
y = x**2

with tf.Session() as sess:
  result = sess.run(y, feed_dict = {x : [[1,2,3], [4,5,6]]})
  print(result)

[[ 1.  4.  9.]
 [16. 25. 36.]]
